branch-defaults:
  default:
    environment: portfolio-env
    group_suffix: null
  master:
    environment: portfolio-env
environment-defaults:
  portfolio-env:
    branch: null
    repository: null
global:
  application_name: eb-portfolio
  branch: null
  default_ec2_keyname: portfolio_key
  default_platform: Python 2.7
  default_region: us-west-1
  profile: eb-cli
  repository: null
  sc: git
